/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appjavaprueba_JavaInterpolacion */

#ifndef _Included_appjavaprueba_JavaInterpolacion
#define _Included_appjavaprueba_JavaInterpolacion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado2
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado2
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado3
 * Signature: (DDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado3
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado4
 * Signature: (DDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado4
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado5
 * Signature: (DDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado5
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado6
 * Signature: (DDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado6
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appjavaprueba_JavaInterpolacion
 * Method:    polinomio_grado7
 * Signature: (DDDDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appjavaprueba_JavaInterpolacion_polinomio_1grado7
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
